services:

  postgres:
    image: postgres:17
    container_name: code-notes-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: code_notes
      POSTGRES_USER: code_notes
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - code_notes_postgres_data:/var/lib/postgresql/data

  backend:
    image: phyriak/code-notes-backend:latest
    container_name: code-notes-backend
    restart: unless-stopped

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: code_notes
      DB_USER: code_notes
      DB_PASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      - postgres
    
    ports:
    - "3200:3200"

  frontend:
    image: phyriak/code-notes-frontend:latest
    container_name: code-notes-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "8085:80"

volumes:
  code_notes_postgres_data: