services:
  postgres:
    image: postgres:17
    container_name: code-notes-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: code_notes
      POSTGRES_USER: code_notes
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - code_notes_postgres_data:/var/lib/postgresql/data

    ports:
      - "55432:5432"

  backend:
    build:
      context: ./backend
    container_name: code-notes-backend
    restart: unless-stopped

    volumes:
      - ./uploads:/app/uploads

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: code_notes
      DB_USER: code_notes
      DB_PASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      - postgres

    ports:
      - "3100:3100"

volumes:
  code_notes_postgres_data: