deploy:

  needs: build

  runs-on: ubuntu-latest

  steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy docker-compose.yml to Hetzner
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HETZNER_HOST }}
        username: ${{ secrets.HETZNER_USER }}
        key: ${{ secrets.HETZNER_SSH_KEY }}
        source: "docker-compose.yml"
        target: "/opt/apps/code-notes"

    - name: Deploy to Hetzner
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.HETZNER_HOST }}
        username: ${{ secrets.HETZNER_USER }}
        key: ${{ secrets.HETZNER_SSH_KEY }}

        script: |
          cd /opt/apps/code-notes

          echo "Pulling latest images..."

          docker compose pull

          echo "Starting Code Notes..."

          docker compose up -d

          echo "Waiting for application..."

          for i in {1..12}; do
            if curl -f http://localhost:8085; then
              echo "Code Notes is UP"

              docker image prune -af

              exit 0
            fi

            echo "Application not ready yet..."
            sleep 10
          done

          echo "Code Notes failed to start"

          docker compose ps

          exit 1